### PR TITLE
improve Beteiligungsverfahren page

### PR DESCRIPTION
**Pull request by der-john**

### CODE REVIEW

**Comment by der-john** [comment]
the image next to 'Bebauungsplanverfahren' is still wrong... I'm having problems: when I upload a new one via the admin interface, and then dump my database, I can't reload it because of some `pk` disorder that has nothing to do with it (as far as I can tell):

> django.db.utils.IntegrityError: Problem installing fixture '/home/john/meinberlin-wagtail/initial_content.json': Could not load contenttypes.ContentType(pk=12): UNIQUE constraint failed: django_content_type.app_label, django_content_type.model

**Comment by der-john** [comment]
in the end, I used an already uploaded image (bplan.png).

**Comment by der-john** [comment]
I inserted the ugly `<br/>` elements so that the headlines would be underneath the image frames. I hope I can change the CSS to reach the same thing.

**Comment by xi** [comment]
LGTM.

**Pull request merged**
