### PR TITLE
adhocracy login

### PR DESCRIPTION
**Pull request by xi**
This implements an adhocracy based user indicator in the wagtail header. Once this is merged, there are only two more things to do:
-  [ ] also show the user indicator in the mobile layout
-  [x] redirect to frontpage after successful login.

### CODE REVIEW

**Comment by der-john** [comment]
On registration, I get an email with the following confirmation link:

http://localhost:6551/static/embed.html#!/activate/Du7XnccZheTW2cEx9skbku_D

@xi: Where can I change this address?

**Comment by xi** [comment]
Did you update your adhocracy config according to the updated README?

**Comment by der-john** [comment]
thanks for reminding me!

**Comment by der-john** [comment]
works. and looks good.

**Pull request merged**
